# Makefile — formatting, linting, and requirements checks.
#
# Scoped to what the repo has today: Markdown, YAML, and Doorstop requirements.
# Rust and Node/React targets will be added when implementation starts (see
# .devcontainer/README.md). Modelled on the qrusty Makefile.
#
# All tools are provided by the dev container (.devcontainer) — run inside it.

.DEFAULT_GOAL := help

MARKDOWNLINT := markdownlint-cli2
PRETTIER     := prettier
YAMLLINT     := yamllint
# provreq validates its own requirements now that they live in a ReqForge project (#321): every
# artifact loads, collection configs are valid, and no two artifacts share a uuid. Promotes soft
# diagnostics to errors, the way `doorstop -e` did — a project that loads with warnings is not
# validated.
PROVREQ       = $(CARGO) run --quiet --bin provreq --
TRACE_REPORT := docs/traceability_report.md
CARGO        := cargo
NPM          := npm --prefix web

# Prettier ignores come from .prettierignore; markdownlint/yamllint exclusions
# are passed explicitly below. The qrusty symlink and generated dirs are always
# excluded so we never lint/format outside this repo.

.PHONY: help check-tools \
	fmt fmt-check lint pre-merge setup-hooks check-requirements \
	fmt-md fmt-check-md lint-md \
	fmt-yaml fmt-check-yaml lint-yaml \
	traceability traceability-report \
	web rust-check audit build test

help:
	@echo "Targets:"
	@echo "  check-tools         Verify the dev toolchain is present and runnable"
	@echo "  fmt                 Format Markdown + YAML (prettier --write)"
	@echo "  fmt-check           Check formatting without writing"
	@echo "  lint                Lint Markdown (markdownlint) + YAML (yamllint)"
	@echo "  check-requirements  Validate requirements + fail on orphan tags (provreq check)"
	@echo "  traceability        Print a requirements traceability report (provreq report)"
	@echo "  traceability-report Write the report to $(TRACE_REPORT)"
	@echo "  web                 Build the frontend into web/dist (embedded by cargo)"
	@echo "  rust-check          cargo fmt --check, clippy -D warnings, and tests"
	@echo "  audit               cargo audit + npm audit — scan dependencies for known CVEs"
	@echo "  build               Build the frontend, then the release binary"
	@echo "  test                Build the frontend, then run cargo + vitest suites"
	@echo "  pre-merge           Preflight: traceability, fmt, lint, requirements, frontend, rust, audit"
	@echo "                      (check-requirements now covers the orphan-tag check)"
	@echo "  setup-hooks         Install git hooks (core.hooksPath -> .githooks)"
	@echo ""
	@echo "  Per-language: fmt-md fmt-check-md lint-md  fmt-yaml fmt-check-yaml lint-yaml"

# --- environment ---
check-tools:
	@bash scripts/validate_dependencies.sh

# --- aggregates ---
# `fmt` covers every language the repo formats, Rust included: pre-merge runs `fmt` at step
# 2 and `cargo fmt --check` (inside rust-check) at step 8, so a `fmt` that skipped Rust made
# the gate fail on exactly what its own earlier step claimed to have fixed.
fmt: fmt-md fmt-yaml fmt-rust
fmt-check: fmt-check-md fmt-check-yaml
lint: lint-md lint-yaml

# --- Rust ---
# Only the formatter lives here; rust-check owns the checking side (fmt-check, clippy, test).
fmt-rust:
	@cargo fmt

# --- Markdown ---
fmt-md:
	@$(PRETTIER) --write --ignore-unknown --ignore-path .prettierignore "**/*.md"

fmt-check-md:
	@$(PRETTIER) --check --ignore-unknown --ignore-path .prettierignore "**/*.md"

# docs/traceability_report.md is generated by `provreq report` (make traceability-report), so it is
# excluded from the prose linter like the other generated/managed trees — its shape is provreq's to
# decide, not the linter's.
lint-md:
	@$(MARKDOWNLINT) "**/*.md" "!qrusty/**" "!requirements/**" "!docs/traceability_report.md" "!**/node_modules/**" "!.venv/**" "!.claude/**" "!.claude-home/**"

# --- YAML ---
# --no-error-on-unmatched-pattern: the repo has only `.yml` today, and prettier >=3 errors on a
# glob that matches nothing — so the `**/*.yaml` arm must not fail when no such file exists yet.
fmt-yaml:
	@$(PRETTIER) --write --ignore-unknown --no-error-on-unmatched-pattern --ignore-path .prettierignore "**/*.yml" "**/*.yaml"

fmt-check-yaml:
	@$(PRETTIER) --check --ignore-unknown --no-error-on-unmatched-pattern --ignore-path .prettierignore "**/*.yml" "**/*.yaml"

lint-yaml:
	@$(YAMLLINT) -c .yamllint.yml .

# --- Requirements ---
check-requirements:
	@$(PROVREQ) check .

traceability:
	@$(PROVREQ) report .

# The report is a committed, browseable artifact regenerated from `provreq report` (was
# scripts/traceability.py, retired once provreq owned traceability). The orphan-tag check it used to
# carry is now part of `check-requirements` (`provreq check` fails on a tag naming an unknown
# requirement), so there is no separate traceability-check target.
traceability-report:
	@$(PROVREQ) report . > $(TRACE_REPORT)

# --- Frontend + Rust ---
# The frontend must build BEFORE cargo: `cargo build` embeds web/dist via
# rust-embed, so the real UI has to exist on disk first.
web:
	@$(NPM) ci
	@$(NPM) run build

rust-check:
	@$(CARGO) fmt --check
	@$(CARGO) clippy --all-targets -- -D warnings
	@$(CARGO) test --all

# Scan both dependency trees for known CVEs — Rust via the RustSec advisory DB, justified by the
# HTTP/TLS stack (reqwest, rustls) pulled in for the LLM classifier; npm because the binary embeds
# web/dist, so an unaudited frontend tree is an unaudited release. While this target ran only
# `cargo audit`, the frontend carried a high-severity `nanoid` and a moderate `postcss` advisory
# and the gate reported itself clean.
audit:
	@$(CARGO) audit
	@$(NPM) audit

build: web
	@$(CARGO) build --release

test: web
	@$(CARGO) test --all
	@$(NPM) test

# --- Preflight ---
pre-merge:
	@echo "=== pre-merge preflight ==="
	@echo "Manual prerequisite (not automated): update docs and requirements for the changes being merged."
	@echo ""
	@echo "[1/8] traceability-report (regenerate $(TRACE_REPORT))"
	@$(MAKE) --no-print-directory traceability-report
	@echo "[2/8] fmt"
	@$(MAKE) --no-print-directory fmt
	@echo "[3/8] fmt-check"
	@$(MAKE) --no-print-directory fmt-check
	@echo "[4/8] lint"
	@$(MAKE) --no-print-directory lint
	@echo "[5/8] check-requirements (validate + no orphan tags)"
	@$(MAKE) --no-print-directory check-requirements
	@echo "[6/8] web (build frontend into web/dist)"
	@$(MAKE) --no-print-directory web
	@echo "[7/8] rust-check (fmt-check, clippy -D warnings, cargo test)"
	@$(MAKE) --no-print-directory rust-check
	@echo "[8/8] audit (cargo audit + npm audit — dependency CVEs)"
	@$(MAKE) --no-print-directory audit
	@echo ""
	@echo "=== pre-merge passed ==="

setup-hooks:
	@git config core.hooksPath .githooks
	@echo "Installed: core.hooksPath -> .githooks (pre-commit runs fmt-check, lint, check-requirements)"
