# Makefile — formatting, linting, and requirements checks.
#
# Scoped to what the repo has today: Markdown, YAML, and Doorstop requirements.
# Rust and Node/React targets will be added when implementation starts (see
# .devcontainer/README.md). Modelled on the qrusty Makefile.
#
# All tools are provided by the dev container (.devcontainer) — run inside it.

.DEFAULT_GOAL := help

MARKDOWNLINT := markdownlint-cli2
PRETTIER     := prettier
YAMLLINT     := yamllint
DOORSTOP     := doorstop
TRACEABILITY := uv run scripts/traceability.py
TRACE_REPORT := docs/traceability_report.md
CARGO        := cargo
NPM          := npm --prefix web

# Prettier ignores come from .prettierignore; markdownlint/yamllint exclusions
# are passed explicitly below. The qrusty symlink and generated dirs are always
# excluded so we never lint/format outside this repo.

.PHONY: help check-tools \
	fmt fmt-check lint pre-merge setup-hooks check-requirements \
	fmt-md fmt-check-md lint-md \
	fmt-yaml fmt-check-yaml lint-yaml \
	traceability traceability-report traceability-check \
	web rust-check audit build test

help:
	@echo "Targets:"
	@echo "  check-tools         Verify the dev toolchain is present and runnable"
	@echo "  fmt                 Format Markdown + YAML (prettier --write)"
	@echo "  fmt-check           Check formatting without writing"
	@echo "  lint                Lint Markdown (markdownlint) + YAML (yamllint)"
	@echo "  check-requirements  Validate the Doorstop requirements tree"
	@echo "  traceability        Print a requirements traceability report"
	@echo "  traceability-report Write the report to $(TRACE_REPORT)"
	@echo "  traceability-check  Fail if any code tag references an unknown requirement"
	@echo "  web                 Build the frontend into web/dist (embedded by cargo)"
	@echo "  rust-check          cargo fmt --check, clippy -D warnings, and tests"
	@echo "  audit               cargo audit — scan dependencies for known CVEs"
	@echo "  build               Build the frontend, then the release binary"
	@echo "  test                Build the frontend, then run cargo + vitest suites"
	@echo "  pre-merge           Preflight: traceability, fmt, lint, requirements, frontend, rust, audit"
	@echo "  setup-hooks         Install git hooks (core.hooksPath -> .githooks)"
	@echo ""
	@echo "  Per-language: fmt-md fmt-check-md lint-md  fmt-yaml fmt-check-yaml lint-yaml"

# --- environment ---
check-tools:
	@bash scripts/validate_dependencies.sh

# --- aggregates ---
fmt: fmt-md fmt-yaml
fmt-check: fmt-check-md fmt-check-yaml
lint: lint-md lint-yaml

# --- Markdown ---
fmt-md:
	@$(PRETTIER) --write --ignore-unknown --ignore-path .prettierignore "**/*.md"

fmt-check-md:
	@$(PRETTIER) --check --ignore-unknown --ignore-path .prettierignore "**/*.md"

# docs/traceability_report.md is generated by scripts/traceability.py; it uses
# <br> to stack multiple trace locations in a table cell, so it is exempt from
# the prose linter (MD033) just like the other generated/managed trees.
lint-md:
	@$(MARKDOWNLINT) "**/*.md" "!qrusty/**" "!requirements-doorstop/**" "!docs/traceability_report.md" "!**/node_modules/**" "!.venv/**" "!.claude/**" "!.claude-home/**"

# --- YAML ---
fmt-yaml:
	@$(PRETTIER) --write --ignore-unknown --ignore-path .prettierignore "**/*.yml" "**/*.yaml"

fmt-check-yaml:
	@$(PRETTIER) --check --ignore-unknown --ignore-path .prettierignore "**/*.yml" "**/*.yaml"

lint-yaml:
	@$(YAMLLINT) -c .yamllint.yml .

# --- Requirements ---
check-requirements:
	@$(DOORSTOP)

traceability:
	@$(TRACEABILITY)

traceability-report:
	@$(TRACEABILITY) --output $(TRACE_REPORT)

traceability-check:
	@$(TRACEABILITY) --check >/dev/null

# --- Frontend + Rust ---
# The frontend must build BEFORE cargo: `cargo build` embeds web/dist via
# rust-embed, so the real UI has to exist on disk first.
web:
	@$(NPM) ci
	@$(NPM) run build

rust-check:
	@$(CARGO) fmt --check
	@$(CARGO) clippy --all-targets -- -D warnings
	@$(CARGO) test --all

# Scan the dependency tree for known CVEs (RustSec advisory DB). Justified by the
# HTTP/TLS stack (reqwest, rustls) pulled in for the LLM classifier.
audit:
	@$(CARGO) audit

build: web
	@$(CARGO) build --release

test: web
	@$(CARGO) test --all
	@$(NPM) test

# --- Preflight ---
pre-merge:
	@echo "=== pre-merge preflight ==="
	@echo "Manual prerequisite (not automated): update docs and requirements for the changes being merged."
	@echo ""
	@echo "[1/9] traceability-report (regenerate $(TRACE_REPORT))"
	@$(MAKE) --no-print-directory traceability-report
	@echo "[2/9] fmt"
	@$(MAKE) --no-print-directory fmt
	@echo "[3/9] fmt-check"
	@$(MAKE) --no-print-directory fmt-check
	@echo "[4/9] lint"
	@$(MAKE) --no-print-directory lint
	@echo "[5/9] check-requirements"
	@$(MAKE) --no-print-directory check-requirements
	@echo "[6/9] traceability-check (no orphan tags)"
	@$(MAKE) --no-print-directory traceability-check
	@echo "[7/9] web (build frontend into web/dist)"
	@$(MAKE) --no-print-directory web
	@echo "[8/9] rust-check (fmt-check, clippy -D warnings, cargo test)"
	@$(MAKE) --no-print-directory rust-check
	@echo "[9/9] audit (cargo audit — dependency CVEs)"
	@$(MAKE) --no-print-directory audit
	@echo ""
	@echo "=== pre-merge passed ==="

setup-hooks:
	@git config core.hooksPath .githooks
	@echo "Installed: core.hooksPath -> .githooks (pre-commit runs fmt-check, lint, check-requirements)"
