import { useState } from "react";

import type { ArtifactDetail, BlobDetail } from "../../api/types";
import { ReplaceBlobDialog } from "./ReplaceBlobDialog";

interface Props {
  readonly artifact: ArtifactDetail;
}

const INLINE_MEDIA_TYPES = new Set([
  "application/pdf",
  "image/png",
  "image/jpeg",
  "image/gif",
  "image/svg+xml",
]);

/// Split the three-tier preview logic from UX-uploadPreview so the
/// component only renders what it's been given, and tests pick up
/// each branch without having to construct a matching blob
/// backend.
type PreviewTier = "inline" | "thumbnail" | "icon-only";

function tierForMediaType(mediaType: string): PreviewTier {
  if (INLINE_MEDIA_TYPES.has(mediaType)) return "inline";
  if (mediaType.startsWith("application/vnd.openxmlformats-officedocument"))
    return "thumbnail";
  return "icon-only";
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let value = bytes / 1024;
  let unitIdx = 0;
  while (value >= 1024 && unitIdx < units.length - 1) {
    value /= 1024;
    unitIdx += 1;
  }
  return `${value.toFixed(value >= 10 ? 0 : 1)} ${units[unitIdx]}`;
}

// Implements: ART006 — tiered preview: inline for browser-native media,
// server thumbnail otherwise, icon + download as the floor.
export function BlobArtifactView({ artifact }: Props) {
  const [isReplaceOpen, setReplaceOpen] = useState(false);
  const blob = artifact.blob;
  if (!blob) {
    return (
      <p className="text-sm text-slate-500">
        Blob metadata missing — the sidecar failed to load.
      </p>
    );
  }

  const tier = tierForMediaType(blob.mediaType);
  return (
    <div className="space-y-4">
      <BlobHeader
        blob={blob}
        onReplace={() => setReplaceOpen(true)}
        fileName={`${artifact.name}${blob.mediaType ? extensionFromMedia(blob.mediaType) : ""}`}
      />
      {tier === "inline" ? <InlinePreview blob={blob} /> : null}
      {tier === "thumbnail" ? <ThumbnailPreview blob={blob} /> : null}
      {tier === "icon-only" ? <IconOnlyPreview blob={blob} /> : null}
      {isReplaceOpen ? (
        <ReplaceBlobDialog
          artifact={artifact}
          onClose={() => setReplaceOpen(false)}
        />
      ) : null}
    </div>
  );
}

function BlobHeader({
  blob,
  onReplace,
  fileName,
}: {
  blob: BlobDetail;
  onReplace: () => void;
  fileName: string;
}) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-2 rounded border border-slate-200 bg-slate-50 p-3 text-sm dark:border-slate-800 dark:bg-slate-900">
      <div>
        <span className="font-mono text-slate-700 dark:text-slate-300">
          {fileName}
        </span>
        <span className="ml-2 text-slate-500">
          {blob.mediaType} · {formatBytes(blob.byteSize)}
        </span>
      </div>
      <div className="flex gap-2">
        <a
          href={blob.downloadUrl}
          className="rounded border border-slate-300 px-2 py-1 text-xs hover:bg-slate-100 dark:border-slate-600 dark:hover:bg-slate-800"
          download
        >
          Download
        </a>
        <button
          type="button"
          onClick={onReplace}
          className="rounded bg-slate-900 px-2 py-1 text-xs text-white hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-900"
        >
          Replace file
        </button>
      </div>
    </div>
  );
}

function InlinePreview({ blob }: { blob: BlobDetail }) {
  if (blob.mediaType.startsWith("image/")) {
    return (
      <img
        src={blob.downloadUrl}
        alt=""
        className="max-h-[70vh] w-auto rounded border border-slate-200 dark:border-slate-800"
      />
    );
  }
  // PDF falls through to an iframe — the browser's bundled PDF
  // viewer handles paging + zoom + print in-place.
  return (
    <iframe
      src={blob.downloadUrl}
      title="Blob preview"
      className="h-[75vh] w-full rounded border border-slate-200 dark:border-slate-800"
    />
  );
}

function ThumbnailPreview({ blob }: { blob: BlobDetail }) {
  return (
    <div className="flex flex-col items-start gap-3 rounded border border-slate-200 p-3 dark:border-slate-800">
      <ThumbnailImage blob={blob} />
      <p className="text-xs text-slate-500">
        Preview generated by the container's thumbnailer. Download for full
        fidelity.
      </p>
    </div>
  );
}

function ThumbnailImage({ blob }: { blob: BlobDetail }) {
  const [failed, setFailed] = useState(false);
  if (failed) {
    return (
      <p className="text-sm text-slate-500" role="status">
        No thumbnailer for this format — use the Download button above.
      </p>
    );
  }
  return (
    <img
      src={blob.thumbnailUrl}
      alt="thumbnail"
      className="max-h-96 w-auto rounded border border-slate-200 dark:border-slate-800"
      onError={() => setFailed(true)}
    />
  );
}

function IconOnlyPreview({ blob }: { blob: BlobDetail }) {
  return (
    <div className="flex items-start gap-3 rounded border border-slate-200 p-4 text-sm text-slate-700 dark:border-slate-800 dark:text-slate-300">
      <span
        aria-hidden
        className="flex h-12 w-12 items-center justify-center rounded bg-slate-200 text-xl font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300"
      >
        FILE
      </span>
      <div>
        <p>
          ReqForge doesn't have a thumbnailer for{" "}
          <span className="font-mono">{blob.mediaType}</span> in the running
          container. Use the Download button to view the file in its native
          application.
        </p>
        <p className="mt-1 text-xs text-slate-500">
          {formatBytes(blob.byteSize)} · SHA-256{" "}
          <span className="font-mono">{blob.contentHash.slice(0, 12)}…</span>
        </p>
      </div>
    </div>
  );
}

function extensionFromMedia(mediaType: string): string {
  // Purely cosmetic — the display name pairs the artifact's name
  // with a guessed suffix so operators see what they uploaded. The
  // sidecar carries the canonical extension via blobPath, but the
  // DTO doesn't surface that string directly, so we infer.
  switch (mediaType) {
    case "application/pdf":
      return ".pdf";
    case "image/png":
      return ".png";
    case "image/jpeg":
      return ".jpg";
    case "image/gif":
      return ".gif";
    case "image/svg+xml":
      return ".svg";
    case "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
      return ".docx";
    case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
      return ".xlsx";
    case "application/vnd.openxmlformats-officedocument.presentationml.presentation":
      return ".pptx";
    default:
      return "";
  }
}
